kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "dfws-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
