kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: adminsa
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: dfws/nfs
            - name: NFS_SERVER
              value: 192.168.50.32
            - name: NFS_PATH
              value: /home/nfs_data
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.50.32
            path: /home/nfs_data
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dfws-nfs
provisioner: dfws/nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false" # When set to "false" your PVs will not be archived
                           # by the provisioner upon deletion of the PVC.
