kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: slave-m2-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "dfws-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
