apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
    - port: 50000
      name: jnlp
      targetPort: 50000
  selector:
    app: jenkins
